[package]
name = "guccicci"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.53"
rand = "0.8.4"
serde = {version = "1.0.133", features = ["derive"]}
thiserror = "1.0.30"
toml = "0.5.8"
